sudo: required
services:
  - docker

before_install: 
  - docker build -t don2001l/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true don2001l/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react"
  env: "DockerReact-env" 
  bucket_name: elasticbeanstalk-us-east-2-693759577295
  bucket_path: "docker_react"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
