#Base Image
FROM node:alpine

# Add files required to Image
WORKDIR /app/docker/project-react-dev/frontend

COPY package.json .

# Depenencies
RUN npm install

COPY . .
# Startup
CMD ["npm", "run", "start"]
