version: "3"
services:
  frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    - /app/docker/project-react-dev/react_client/node_modules
    - ./src:/app/src
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - ./src:/app/src
    - /app/docker/project-react-dev/react_client/node_modules
    command: ["npm", "run", "test"]
