version: "3"
services:
  postgres:
    image: 'postgres:latest'
  redis: 
    restart: always
    image: 'redis:latest'
    ports:
      - "127.0.0.1:6379:6379"
  api:
    depends_on:
      - postgres
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    depends_on:
      - redis
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8090:80"
